apiVersion: v1
kind: Pod
metadata:
  name: strict-success-pod
  namespace: default
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: strict-creds
