apiVersion: v1
kind: Pod
metadata:
  name: ns-fail-pod
  namespace: frontend # Wrong namespace!
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: db-creds-api
