apiVersion: v1
kind: Pod
metadata:
  name: cluster-dev-pod
  namespace: dev
spec:
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
    envFrom:
    - secretRef:
        name: global-creds
