apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-secure
  template:
    metadata:
      labels:
        app: demo-secure
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: demo
          image: nginx:1.21
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
